# This is a basic workflow to help you get started with Actions

name: WakatimeMain

on:
  schedule:    
    # Runs at 12am UTC
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: Updated the Readme
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          SHOW_TITLE: true
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_LINES_OF_CODE: true
          SHOW_PROFILE_VIEWS: false
          SHOW_COMMIT: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_SHORT_INFO: false
          SHOW_LOC_CHART: true
          SHOW_LANGUAGE_PER_REPO: true
